# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine 

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json pnpm-lock.yaml* .npmrc* ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

COPY drizzle ./drizzle
COPY drizzle.config.ts ./drizzle.config.ts

CMD ["pnpm", "drizzle-kit", "migrate"]
